# Generated by Django 4.1 on 2022-10-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_examcenter_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MyExamCenter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.examcenter',),
        ),
    ]
