# Generated by Django 4.1 on 2022-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=30)),
                ('stumail', models.EmailField(max_length=30)),
                ('stupass', models.CharField(max_length=30)),
            ],
        ),
    ]
