# Generated by Django 4.1 on 2022-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
