# Generated by Django 4.1 on 2022-10-24 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_alter_post_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=30)),
                ('song_duration', models.IntegerField()),
                ('user_name', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
