# Generated by Django 4.1 on 2022-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_admdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default='2022-1-18'),
            preserve_default=False,
        ),
    ]
