# Generated by Django 4.1 on 2022-10-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student2_remove_student_admdatetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student2',
        ),
    ]
