# Generated by Django 4.1 on 2022-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_delete_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
                ('passdate', models.DateField()),
                ('admdatetime', models.DateTimeField()),
            ],
        ),
    ]
