# Generated by Django 4.1 on 2022-10-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student2',
            name='admdatetime',
        ),
    ]
