# Generated by Django 4.1 on 2022-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_student2_admdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student2',
            name='admdatetime',
            field=models.DateTimeField(default=12),
            preserve_default=False,
        ),
    ]
