# Generated by Django 4.1 on 2022-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_student_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default='nul'),
            preserve_default=False,
        ),
    ]
