# Generated by Django 4.1.2 on 2022-10-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudoperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workhours', models.IntegerField(max_length=200)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudoperation.employee')),
            ],
        ),
    ]
